name: Parallel Test Build
on: push
jobs:
  Add-Tocart-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      # Install npm dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          command: npx cypress run cypress/e2e/addToCartTest.cy.js

      - name: Cypress Test Report
        uses: actions/upload-artifact@v4
        with:
          name: Mochawesome HTML Report - Add To Cart
          path: cypress/reports/html

  Reg-Flow-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      # Install npm dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          command: npx cypress run cypress/e2e/registerTest.cy.js

      - name: Cypress Test Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: Mochawesome HTML Report - Reg Flow
          path: cypress/reports/html

      - name: Slack Notification
        if: always()
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_COLOR: ${{ job.status }} # or a specific color like 'good' or '#ff00ff'
          SLACK_ICON: https://github.com/rtCamp.png?size=48
          SLACK_MESSAGE: "Test Automation Report https://github.com/piosso1/Cypress-E2E/actions/runs/${{github.run_id}}"
          SLACK_TITLE: Cypress Web Test
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
